version: '3'

services:
  gpt4free-api:
    build: .
    networks:
      - lucy_rede
    ports:
      - "8000:8000"
    environment:
      - WATCHFILES_FORCE_POLLING=true
    command: gunicorn --reload --bind 0.0.0.0:8000 --timeout 300 api:app